### ISSUE TITLE
Support Netflow v9

### ISSUE THREAD

**Issue by henrikjohansen** [graylog-labs/graylog-plugin-netflow#1]
Please consider adding support for netflow v9

**Comment by bernd** [comment]
Yep, that will be the next thing.

**Comment by JakeDEvans** [comment]
sFlow/jFlow support too?

**Comment by bernd** [comment]
Someone on the mailing list asked about IPFIX/AppFlow too. No idea what all of this means yet. :smile: 

The plan is to support the common NetFlow versions which are (too my knowledge) v5 and v9. Please correct me if I am wrong.

@JakeDEvans Please open a new issue for sFlow/jFlow support. Thank you!

**Comment by rcord02** [comment]
I would say IPFIX is a kind of NetFlow v10. It bases on v9, but is not developed by Cisco.
It allows operators to define own fields per template and is a more open replacement for NetFlow.
For a quick overview about the confusing amount of flow protocols this wiki page is quite helpful:
https://en.wikipedia.org/wiki/NetFlow#NetFlow_and_IPFIX
I will create a issue for IPFIX with further information.

**Comment by JakeDEvans** [comment]
@bernd actually, I may not need to, "JFlow and CFlow are the same as CISCO Netflow v5."

according to some random dude on the internet, http://www.flowtraq.com/corporate/resources/whitepapers/the-netflowsflowcflowjflow-flow-dilemma/

**Comment by henrikjohansen** [comment]
@bernd could you provide a rough timeline for v9 support? I'd love to get rid of our last logstash instances :)

**Comment by digger-squared** [comment]
ditto  on v9 support,  ASA's only support v9.

**Comment by akrus** [comment]
+1 :)

**Comment by kre8or69** [comment]
+1 on V9 support

**Comment by marcobelmonte** [comment]
I would build a statue of you and have my children pray to it and my wife sing songs of your conquests for v9 support.

But ya, +1 for me, too ;-)

**Comment by marcobelmonte** [comment]
By th way guys, I discovered that NxLog can also input/output netflow including v9 - something maybe to hold you over until this plugin supports it?

**Comment by JakeDEvans** [comment]
Actually I started using logstash, which takes netflow5/9 and outputs in gelf

**Comment by marcobelmonte** [comment]
So two options exist. NxLog does the same thing, outputs to GELF or whatever else you want... Pick your poison ;-)

**Comment by Lollaskates** [comment]
@marcobelmonte I'm interested in using nxlog as a middle-man to get netflow into graylog. Above you mention it supports netflow, however I don't see any indication of that in the documentation for it. Would you be able to share your config or point me to the right information?

Also, +1 for NetFlowv9 support in this plugin :)

**Comment by marcobelmonte** [comment]
Sorry it took me so long to get back to you on this. In fact, the open source version of NxLog doesn't support this feature but the company I work for has a license for the enterprise version which does. As for documentation, the feature was so new that Botond (the guy who wrote NxLog) had to supply us supplemental documentation that had not made it into the enterprise material yet. Here are the relevant lines in our config for your consideration:

```
<Extension netflow>
 Module xm_netflow
</Extension>

<Extension json>
 Module xm_json
</Extension>

<Input netflowIn1>
 Module im_udp
 Host 0.0.0.0
 Port 2055
 InputType netflow
 Exec parse_json(); $source = $SourceIpAddress; to_json();
</Input>

<Output netflowGelfOut>
 Module om_tcp
 Host <removed for security>
 Port 55514
 OutputType GELF_TCP
</Output>

<Route 2>
 Path netflowIn1 => netflowGelfOut
</Route>
```

Hope that helps, man.

**Comment by bhklimk** [comment]
All

Just made a pull request that had code to support v9.  Please let me know if you need an additional information; this is my first time contributing to an open-source project :).

**Comment by marcobelmonte** [comment]
Nice first contribution, man! You've just made a lot of people happy!

**Comment by PeepOks** [comment]
Extractors of Netflow v9 input does not work. Seems like extractor is unable to read netflow fields value.
I'm trying to remove leading slash( / ) from IPV4_SRC_ADDR and IPV4_DST_ADDR field.

**Comment by pmmivv** [comment]
I agrree, please add support to netflow v9. Let's take graylog to the next level.
In the current moment, graylog is a little raw because the lack of input method support. Netflow, snmp need more development.

Patrick Veiga

**Comment by JakeDEvans** [comment]
Recommend close,  beats do this task extremely well.

**Comment by pmmivv** [comment]
@JakeDEvans, how is beats compatible with netflow? Do you have some toturial or some extra information for that?

PV

**Comment by JakeDEvans** [comment]
packetbeat flows input

**Comment by pmmivv** [comment]
@JakeDEvans , can you be a little more Specific? (some kind off web page, repository, video,...)

**Comment by joschi** [comment]
@pmmivv Please move this discussion to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by tkald** [comment]
@PeepOks 

You can use pipline rules to remove leading slahs ( / ) from source and destination fields:

> rule "fix netflow slashes"
> when
>   has_field("IPV4_SRC_ADDR") && has_field("IPV4_DST_ADDR")
> then
>   
>   let ip_src = substring(to_string($message.IPV4_SRC_ADDR), 1);
>   set_field("IPV4_SRC_ADDR", ip_src);
>   let ip_dst = substring(to_string($message.IPV4_DST_ADDR), 1);
>   set_field("IPV4_DST_ADDR", ip_dst);
> end

Jõudu! ;)
