### ISSUE TITLE
Fortinet netflow

### ISSUE THREAD

**Issue by madchap** [graylog-labs/graylog-plugin-netflow#10]
Hi,

I configured a fortigate appliance per the instructions provided on this page: http://kb.fortinet.com/kb/documentLink.do?externalID=FD36460. I see the traffic coming to graylog with tcpdump, but nothing displays.

Do you know about a possible non-standard here that would cause a drop of the message, making them invisible in graylog?

Thanks for your feedback.

**Comment by joschi** [comment]
@madchap This plugin currently doesn't support Netflow v9 (which FortiOS is using according to http://help.fortinet.com/fos50hlp/52data/Content/FortiOS/fortigate-whats-new-52/system.htm#Netflow).

See #1.
