### ISSUE TITLE
Send Alarm Callback via HTTP alert notification

### ISSUE THREAD

**Issue by artphrases** [graylog-labs/graylog-plugin-netflow#14]
Hi, we are going to use your plugin in our graylogsoftware to check exactly what the plugin is for and want to send the notifications as HTTP alert notification, that Icinga2 is able to read this. Could you give us some advice, what we have to tell our devolpers that they are able to extend your plugin. Thanks in advance Martin

**Comment by joschi** [comment]
@artphrases Alerting has nothing to do with this plugin (which is for consuming NetFlow 5 and 9 into Graylog).

Please check the documentation at http://docs.graylog.org/en/2.3/pages/streams/alerts.html and the Graylog Marketplace, e. g. https://marketplace.graylog.org/addons/fc1b3676-d22b-43ec-a047-cdb93896a0b6

**Comment by artphrases** [comment]
I`m sorry. I put my request into the wrong Queue!
