### ISSUE TITLE
Can't start - requires version 2.3.0

### ISSUE THREAD

**Issue by troykelly** [graylog-labs/graylog-plugin-netflow#15]
The plugin can't appear to start - it seems the version requirement test might not allow for this version?

```
2017-08-05T07:40:00.001Z INFO  [node] [graylog] version[2.4.4], pid[1], build[fcbb46d/2017-01-03T11:33:16Z]
2017-08-05T07:40:01.0010Z ERROR [CmdLineTool] Plugin "NetFlow Plugin" requires version 2.3.0 - not loading!

```

**Comment by joschi** [comment]
@troykelly There are two variants of this plugin, one for Graylog 2.2.x and one for Graylog 2.3.x.

You have to download and install the version of this plugin matching your Graylog version.

**Comment by troykelly** [comment]
Thank you @joschi 
So - there is no plugin for 2.4.x ?

**Comment by joschi** [comment]
@troykelly There is no Graylog 2.4.x yet. Graylog 2.3.0 is the latest version.

The version (2.4.4) printed in the logs you've posted is the version of the embedded Elasticsearch node.
